### ISSUE TITLE
n-speakers改为1后报错

### ISSUE THREAD

**Issue by kokoro-ele** [SUC-DriverOld/so-vits-svc-Chinese-Detaild-Documents#3]
你好，我只想训练一个人物，所以config.json设置如下：
   
```
{...
    "n_speakers": 1
  },
  "spk": {
    "kiri": 0
  }
}
```
但当我进行训练时报错
-- Process 0 terminated with the following error:
Traceback (most recent call last):
```
  File "D:\Anaconda3\envs\sing\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "D:\sing\so-vits-svc\train.py", line 119, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler,
  File "D:\sing\so-vits-svc\train.py", line 202, in train_and_evaluate
    scaler.step(optim_g)
  File "D:\Anaconda3\envs\sing\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 313, in step
    return optimizer.step(*args, **kwargs)
  File "D:\Anaconda3\envs\sing\lib\site-packages\torch\optim\lr_scheduler.py", line 68, in wrapper
    return wrapped(*args, **kwargs)
  File "D:\Anaconda3\envs\sing\lib\site-packages\torch\optim\optimizer.py", line 140, in wrapper
    out = func(*args, **kwargs)
  File "D:\Anaconda3\envs\sing\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\Anaconda3\envs\sing\lib\site-packages\torch\optim\adamw.py", line 162, in step
    adamw(params_with_grad,
  File "D:\Anaconda3\envs\sing\lib\site-packages\torch\optim\adamw.py", line 219, in adamw
    func(params,
  File "D:\Anaconda3\envs\sing\lib\site-packages\torch\optim\adamw.py", line 318, in _single_tensor_adamw
    param.addcdiv_(exp_avg, denom, value=-step_size)
RuntimeError: output with shape [1, 256] doesn't match the broadcast shape [200, 256]
```
是需要改模型的参数吗？

**Comment by kokoro-ele** [comment]
发现问题所在了，使用的底模不匹配，删除G_0.pth与D_0.pth后从0训练就好。
